apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "app.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ include "app.revision" . }}
    app.kubernetes.io/part-of: rse
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        {{- include "app.metricsAnnotations" . | nindent 8 }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      securityContext:
{{- include "app.securitycontext" . | nindent 8 }}
{{- if .Values.image.pullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets.secretName }}
{{- end }}
      containers:
      - name: {{ template "app.name" . }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
          - name: PORT
            value: {{ .Values.service.port | quote }}
          - name: DATABASE_URL
            value: {{ template "app.postgresql.connectionstring" (merge (dict "application" "true") .) }}
          - name: NATS_URL
            value: "{{ .Values.connectionManager.nats.protocol }}://{{ .Values.connectionManager.nats.url }}:{{ .Values.connectionManager.nats.port }}"
          - name: ECSURL
            value: "{{ .Values.connectionManager.elastic.protocol }}://{{ .Values.connectionManager.elastic.url }}:{{ .Values.connectionManager.elastic.port }}/"
          - name: LOG_LEVEL
            value: {{ .Values.log.level | default "INFO" }}
          - name: LOG_ENCODING
            value: {{ .Values.log.encoding | default "json" }}
          - name: POSTGRES_USER
            value: {{ .Values.connectionManager.database.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.connectionManager.database.password }}
          - name: POSTGRES_DB
            value: {{ .Values.connectionManager.database.db }}
          - name: AGENT_URL
            value: "{{ .Values.connectionManager.agent.protocol }}://{{ .Values.connectionManager.agent.host }}:{{ .Values.connectionManager.agent.port }}"
          - name: CONNECTION_MANAGER_URL
            value: "{{ .Values.service.protocol }}://{{ .Values.service.host }}:{{ .Values.service.port }}"


{{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 8 }}
{{- end }}
        ports:
        {{- if .Values.metrics.enabled }}
        - name: monitoring
          containerPort: {{ .Values.metrics.port }}
        {{- end }}
        - name: http
          containerPort: {{ .Values.service.port }}
        readinessProbe:
          httpGet:
            path: /v1/health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 2
          failureThreshold: 2
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
