---
volumePermissions:
  enabled: false
  securityContext:
    runAsUser: auto

primary:
  podSecurityContext:
    enabled: true
  containerSecurityContext:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "400m"
shmVolume:
  chmod:
    enabled: false

auth:
  username: ocm
  password: ocm
  database: ocm
